######################################################################
# Automatically generated by qmake (3.0) ?? 5? 19 15:02:49 2015
######################################################################

TEMPLATE = app
TARGET = parallaxhome
INCLUDEPATH += .
QT += svg
# Input
SOURCES += parallaxhome.cpp
RESOURCES += parallaxhome.qrc
